Repository jenkinsci/collapsing-console-sections-plugin, pull requests merged in 2019-12, with the labels that each got.

#17 Create Jenkinsfile
  Jenkinsfile
Labels: chore

#16 Update the Jenkins core requirement to 2.150.3, use the latest Plugin POM
  pom.xml
Labels: dependencies

#18 Reduce the priority of the Collapsing Console Sections annotator so that it runs after other annotators and takes data injected by them into account
  src/main/java/org/jvnet/hudson/plugins/collapsingconsolesections/CollapsingSectionAnnotator.java
  src/main/java/org/jvnet/hudson/plugins/collapsingconsolesections/CollapsingSectionAnnotatorFactory.java
Labels: bug

#19 Move the plugin documentation from Wiki to GitHub
  .gitignore
  README.md
  docs/OLD_CHANGELOG.md
  docs/images/add.svg
  docs/images/collapsing-console-config.png
  docs/images/console-sections.png
  docs/images/error.svg
  docs/images/information.svg
  docs/images/navigation.png
Labels: documentation

#20 Enable Release Drafter in the repository
  .github/release-drafter.yml
Labels: chore
